In [1]:
import omnixai
import numpy as np
import pandas as pd

In [76]:
df = pd.DataFrame(
    data=[[1, 2, 3, 'male', 'yes'], [4, 5, 6, 'female', 'no'], [4, 2, 1, 'both', 'no']],
    columns=['a', 'b', 'c', 'd', 'label']
)

from omnixai.data.tabular import Tabular

x = Tabular(
    data=df,
    categorical_columns=['d'],
    target_column='label'
)
print(x)

   a  b  c       d label
0  1  2  3    male   yes
1  4  5  6  female    no
2  4  2  1    both    no


In [91]:
from omnixai.preprocessing.tabular import TabularTransform
from omnixai.preprocessing.encode import OneHot, Ordinal, LabelEncoder
from omnixai.preprocessing.normalize import MinMax, Standard

# One-hot encoding for categorical features
# Min-max normalization for continuous-valued features
# Label encoding for the target
transform2 = TabularTransform(
    cate_transform=OneHot(),
    #cont_transform=MinMax(),
    target_transform=LabelEncoder()
)

In [93]:
# Transform
y = transform2.fit(x).transform(x)
print(y)

[[0. 0. 1. 1. 2. 3. 1.]
 [0. 1. 0. 4. 5. 6. 0.]
 [1. 0. 0. 4. 2. 1. 0.]]


In [98]:
f = transform2.get_feature_names()
print(f)

['d_both', 'd_female', 'd_male', 'a', 'b', 'c']
